[package]
name = "option_pricing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.16"
gauss-quad = "0.1.4"
roots = "0.0.7"
itertools = "0.10.5"
itertools-num = "0.1.3"
plotters = "0.3.4"